const MARCAS = [
  "3M", "ACRILEX", "ADAMS", "ALLEANZA", "ALPES", "ALPHA", "ALPHA OFFICE", 
  "AMBROSOLI", "AMERICANO", "ANDES", "ANDINA", "APOLO", "APOLO MAX", "APU", 
  "ARCO IRIS", "ARCOR", "AROMA TROPICAL", "ARTESCO", "ARTI", "ARTLINE", 
  "ARTWORK", "ATLAS", "AVAL", "BALLERINA", "BANTEX", "BESKO", "BI-OFFICE",
  "BIC", "BISILQUE", "BMG", "BOMEIJIA", "BROTHER", "BRUÑO", "BUCKY SNACKS",
  "CAMY COLORS", "CANON", "CANSON", "CASIO", "CBIT", "CHAMEX", "CHARITO", 
  "CLASSIC", "COLLEGE", "COLOMBINA", "COMERCIAL LI", "CONFITECA", "CONTI", 
  "CONTROL Z", "COPIMAX", "COPY LASER", "COQUITO", "COSTA", "CRAYOLA", 
  "CREARTE", "CREMINO", "CRISLI", "CYGNUS", "DELY CORP", "DESINFEX",
  "DEYELLI", "DIALE", "DIDACTICA", "DISCOVERY", "DONOFRIO", "DRAGON", 
  "DUCK TAPE", "DURACELL", "DURAFAN", "ECLIPSE", "EDUKT", "EINS", "EMERALD",
  "EPAPER", "EPSON", "EVAFLEX", "EXCELLENT", "EZEL", "FABER CASTELL", 
  "FABRIANO", "FACUNDO", "FALESSA", "FAMILY DOCTOR", "FAVORITA", "FEDRIGONI",
  "FIESTA", "FILGO", "FINI", "FIRSTDOC", "FROVI", "FRUSEC", "GALAXY", 
  "GALLO", "GALLOCOPY", "GEMA", "GLOSSY", "GN", "GRAFICA", "GRAFIPAPEL",
  "HALLS", "HP", "IMPORTADO", "INBOX", "INDIGO", "INKA COLA", "INKJET",
  "INTI", "INVICTUS", "IRIS COLORS", "ITEC", "JACKYPEN", "JOMAR", "JUSTUS",
  "KAPECI", "KEROCOPY", "KINGSTON", "KLIER", "KREATEC", "KUM", "LANGUO", 
  "LAYCONSA", "LIBRO", "LUXOR", "M & M", "MAPED", "MARAT", "MARK BOOK",
  "MARSAR", "MAXELL", "MAXIFAN", "MAYLIN", "MILLENIUM", "MONDI", "N/E", 
  "NATURA", "NAV", "NESTLE", "NILO", "NO ESPECIFICADO", "NORMA", "NORPAL",
  "NOTEX", "NUEVO MUNDO", "OBRAS", "OLEGO", "ONE", "ONLINE", "OVE", "OXFORD",
  "PANASA", "PANASONIC", "PARAMONGA", "PARQUE", "PARROTS", "PEGAFAN",
  "PEGAFLEX", "PERQUIS", "PERUPACK", "PIERRE CARDIN", "PILOT", "PIMAL",
  "POSCA", "PRIMAVERA", "PRISMA", "RANCÉS SOPENA", "RAPID", "REPORT", 
  "ROSITA", "ROTRING", "ROYAL PAPER", "S/M", "SABONIS", "SADIPAL", "SARAGRAF",
  "SCOOL", "SCORPIO", "SHURT", "STABILO", "STAEDTLER", "STANFORD", "STHILO 43",
  "STOR", "SUBLIME", "SURCO", "SYLOON", "TITANIO", "TONG CHANG", "TOP",
  "TP-WHITE PLUS", "TRULULU", "TUINIES", "UHU", "ULTRACOPY", "UNI BALL", 
  "UNIMUNDO", "USO DIARIO", "VALMAR", "VICTORI", "VICTORIA (ALEMAN)", 
  "VIKINGO", "VINIBALL", "VINIFAN", "WINGO", "WINTERS", "WORLD EDICIONES",
  "WT", "XEROX", "XPERT", "XTREM", "YIMI"
];

// Lista de líneas (ejemplo, pon las tuyas completas)
const LINEAS = [
  "ROMPECABEZAS", "JUEGOS", "JUEGOS DIDACTICOS", "CUADERNOS", "COLORES", 
  "PAPELES", "UTILES ESCOLARES"
];
